spring:
  application:
    name: food-delivery-system

  # PostgreSQL Configuration (For Orders)
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: root
    password: password # Change this if your docker-compose uses a different password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # This is the magic command that creates your tables automatically
    show-sql: true # This will print the generated SQL to your console so you can see it working
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # MongoDB Configuration (For Restaurants)
  mongodb:
    uri: mongodb://localhost:27022/restaurant_db
    auto-index-creation: true
  # Redis Configuration (For Caching)
  redis:
    host: localhost
    port: 6379

  # Kafka Configuration (For Event Messaging)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: food-delivery-group

  #Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: gouravchoudhary7442@gmail.com
    password: hehn mequ xmbd imua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
  host: localhost
  servlet:
    context-path: /application